name: 哔咔漫画自动打哔咔

on:
    workflow_dispatch:
    schedule:
        - cron: "00 09 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        #runs-on: ubuntu-22.04
        #if: github.event.repository.owner.id == github.event.sender.id || github.actor == 'BlueSkyClouds'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "初始化Python"
              uses: actions/setup-python@v5
              with:
                python-version: 3.9

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行 哔咔漫画自动打哔咔"
              run: python3 function/bika/bika.py
              env:
                  BIKA_USER: ${{ secrets.BIKA_USER }}
                  BIKA_PASS: ${{ secrets.BIKA_PASS }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
                  
            - name: "Create date file and amend last commit"
              run: |
                TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S' > date
                git config --global user.email "bot@example.com"
                git config --global user.name "bot"
                git add date
                git commit --no-edit
                git push origin master --force-with-lease
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#最后推送 2021年9月20日
